services:
  - type: web
    name: terex-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GCP_PROJECT_ID
        value: terex-neosoft-poc
      - key: GCP_REGION
        value: us-central1
